### ISSUE TITLE
Too many files open error

### ISSUE THREAD

**Issue by mkery** [mkery/Verdant-Log#10]
After opening maybe 5-10 different notebooks, even though all but a few are closed, get this error:

[E 19:50:31.961 LabApp] 500 POST /api/sessions?1573260631948 (::1) 7.92ms referer=http://localhost:8889/lab
[E 19:50:36.284 LabApp] Uncaught exception POST /api/sessions?1573260636275 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri='/api/sessions?1573260636275', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/jupyter_client/manager.py", line 240, in start_kernel
        self.write_connection_file()
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/jupyter_client/connect.py", line 476, in write_connection_file
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/site-packages/jupyter_client/connect.py", line 99, in write_connection_file
      File "/Users/mkery/miniconda/envs/log/lib/python3.7/socket.py", line 151, in __init__
    OSError: [Errno 24] Too many open files

**Comment by mkery** [comment]
https://github.com/jupyterlab/jupyterlab/issues/6727

Seems to be a broader problem with Jupyter?
